# molecule/integration/create.yml
---
- name: Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Proxmox VM
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        node: "{{ lookup('env', 'PROXMOX_NODE') }}"
        name: "monitor-integration"
        newid: "{{ proxmox_vmid }}"
        clone: "debian-12-template"
        full: no
        timeout: 300
        state: present
      register: vm_facts

    - name: Wait for clone to complete
      pause:
        seconds: 10

    - name: Update VM network configuration
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        node: "{{ lookup('env', 'PROXMOX_NODE') }}"
        vmid: "9200"
        ipconfig:
          ipconfig0: "ip=192.168.101.91/24,gw=192.168.101.254"
        update: yes

    - name: Start the VM
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        node: "{{ lookup('env', 'PROXMOX_NODE') }}"
        vmid: "9200"
        state: started
        timeout: 300

    - name: Wait for VM to boot
      pause:
        seconds: 30

    - name: Wait for SSH
      wait_for:
        host: "192.168.101.91"
        port: 22
        timeout: 300
