---
- name: Debian Linux install block
  become: true
  block:
    - name: Ensure the keyring file exists (older)
      ansible.builtin.file:
        path: /etc/apt/keyrings
        mode: "0755"
        state: directory

    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        url: https://repos.influxdata.com/influxdata-archive.key
        keyring: /etc/apt/trusted.gpg.d/influxdata-archive.gpg

    - name: "Setup influxdb apt repo"
      ansible.builtin.copy:
        src: influxdata.list
        dest: /etc/apt/sources.list.d/influxdata.list

    - name: "Get {{ package }}} package"
      ansible.builtin.apt:
        update_cache: true
        name: "{{ package }}"
      register: pkg_install_result
