---
- name: Install prerequisites
  hosts: molecule
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: containers.podman.podman

  tasks:
    #
    # ..........................................................................
    - name: Wait for container to be ready
      wait_for:
        port: 22
        timeout: 30
      when: ansible_connection == 'containers.podman.podman'

    # ..........................................................................
    - name: Branch on Debian
      when: ansible_distribution == "Debian"
      block:
        - name: Install required packages
          apt:
            name:
              - gpg
              - ca-certificates
              - qemu-guest-agent
              - lsof
            update_cache: yes
            state: present

        - name: Ensure qemu-guest-agent is running
          systemd:
            name: qemu-guest-agent
            state: started
            enabled: true

    # ..........................................................................
    - name: Branch on Rocky
      when: ansible_distribution == "Rocky"
      block:
        - name: Install required packages
          dnf:
            name:
              - lsof
            update_cache: yes
            state: present

    - name: Fail for unsupported distribution
      fail:
        msg: "Distribution {{ ansible_distribution }} not supported"
      when: ansible_distribution != "Debian" and ansible_distribution != "Rocky"

    # ===========================================================================
    - name: Ensure systemd is available in container
      command: systemctl --version
      changed_when: false
      register: systemd_check
      failed_when: systemd_check.rc != 0

    - name: Configure container for systemd operation
      command: systemctl daemon-reexec
      when: systemd_check is success
