# molecule/shared/molecule.yml
---
dependency:
  name: galaxy
  options:
    requirements-file: ../../shared/requirements.yml

driver:
  name: default

platforms:
  - name: ${MOLECULE_SCENARIO_NAME}
    vmid: "9200"

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: roles
      interpreter_python: auto_silent
      host_key_checking: false
  playbooks:
    create: ../../shared/create.yml
    prepare: ../../shared/prepare.yml
    destroy: ../../shared/destroy.yml

verifier:
  name: ansible
