---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Debug information
      debug:
        msg:
          - "Playbook dir: {{ playbook_dir }}"
          - "Roles path: {{ playbook_dir }}/../../roles"
          - "Project_root: {{ project_root }}"
          - "Distribution: {{ ansible_distribution }}"

    - name: Include influxdb role
      include_role:
        name: "{{ project_root }}/roles/influxdb"

    - name: Include telegraf role
      include_role:
        name: "{{ project_root }}/roles/telegraf"
