---
dependency:
  name: galaxy
  options:
    requirements-file: ../../molecule/shared/requirements.yml
    ignore-errors: true

driver:
  name: default

platforms:
  - name: "uut-ct"
    image: "gitea.a0a0.org:3001/jackaltx/testing-containers/rocky93-ssh:latest"
    pull: true
    pull_policy: "missing"
    privileged: true # Needed for systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

provisioner:
  name: ansible
  playbooks:
    create: "../../molecule/shared/podman/create.yml"
    prepare: "../../molecule/shared/podman/prepare.yml"
    destroy: "../../molecule/shared/podman/destroy.yml"
  log: true
  config_options:
    defaults:
      roles_path: roles
      interpreter_python: auto_silent
      host_key_checking: false
  inventory:
    group_vars:
      all:
        project_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        report_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/verify_output"
    host_vars:
      uut-ct:
        ansible_connection: podman
        ansible_user: "${USER}"

        influxdb_test: true
        influxdb_configure: true
        telgraf2influxdb_configs:
          {
            "localhost":
              {
                "url": "http://127.0.0.1",
                "token": "",
                "bucket": "telegraf",
                "org": "lavnet",
                "namedrop": '["influxdb_oss"]',
                "bucket_tag": "",
                "exclude_bucket_tag": "",
                "ping_timeout": "0s",
                "read_idle_timeout": "0s",
                "insecure_skip_verify": false,
              },
          }

scenario:
  name: proxmox-metrics
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: ansible
