---
dependency:
  name: galaxy
  options:
    requirements-file: ../../molecule/shared/requirements.yml
    ignore-errors: true

driver:
  name: podman
  options:
    managed: true

platforms:
  # - name: "uut-ct"
  #   image: "gitea.a0a0.org:3001/jackaltx/testing-containers/rocky93-ssh:latest"
  #   network: monitoring-net
  #   ssh_port: 2222
  - name: "uut-ct"
    image: "gitea.a0a0.org:3001/jackaltx/testing-containers/debian12-ssh:latest"
    network: monitoring-net
    command: "/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/tmp
    cgroupns_mode: host
    ssh_host: "127.0.0.1"
    ssh_port: 2222
    ssh_user: "jackaltx"

provisioner:
  name: ansible
  log: true
  env:
    # ANSIBLE_SSH_ARGS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    ANSIBLE_SSH_ARGS: "-o IdentityFile=~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  playbooks:
    create: "../../molecule/shared/podman/create.yml"
    prepare: "../../molecule/shared/podman/prepare_debug.yml"
    destroy: "../../molecule/shared/podman/destroy.yml"
  config_options:
    defaults:
      roles_path: roles
      interpreter_python: auto_silent
      host_key_checking: false
  inventory:
    group_vars:
      all:
        project_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
        report_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/verify_output"
    host_vars:
      uut-ct:
        ansible_connection: ssh
        ansible_user: "jackaltx" # "${USER}"
        # DEBUG: Add explicit SSH settings
        # ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        # ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_ssh_common_args: "-o IdentityFile=~/.ssh/id_ed25519"
        ansible_ssh_private_key_file: "~/.ssh/id_ed25519"

        influxdb_test: true
        influxdb_configure: true
        telgraf2influxdb_configs:
          {
            "localhost":
              {
                "url": "http://127.0.0.1",
                "token": "",
                "bucket": "telegraf",
                "org": "lavnet",
                "namedrop": '["influxdb_oss"]',
                "bucket_tag": "",
                "exclude_bucket_tag": "",
                "ping_timeout": "0s",
                "read_idle_timeout": "0s",
                "insecure_skip_verify": false,
              },
          }

scenario:
  name: podman-metrics
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: ansible
