- name: Converge
  hosts: all
  become: true
  vars:
    loki_local_storage: true
    project_root: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
  tasks:
    - name: Debug information
      debug:
        msg:
          - "Playbook dir: {{ playbook_dir }}"
          - "Roles path: {{ playbook_dir }}/../../roles"
          - "Project_root: {{ project_root }}"

    - name: Include loki role
      ansible.builtin.include_role:
        name: "{{ project_root }/loki"
