# molecule/github/molecule.yml
---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    ignore-errors: true

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      host_key_checking: false
  inventory:
    group_vars:
      all:
        # From proxmox-metrics
        proxmox_vmid: 9100
        project_root: ${MOLECULE_PROJECT_DIRECTORY}
        report_root: ${MOLECULE_PROJECT_DIRECTORY}/verify_output
        telgraf2influxdb_configs:
          localhost:
            url: "http://127.0.0.1"
            token: ""
            bucket: "telegraf"
            org: "lavnet"
            namedrop: '["influxdb_oss"]'
            bucket_tag: ""
            exclude_bucket_tag: ""
            ping_timeout: "0s"
            read_idle_timeout: "0s"
            insecure_skip_verify: false

        # From proxmox-logs
        loki_local_storage: true

scenario:
  name: github
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
