---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    ignore-errors: true

driver:
  name: docker
  options:
    managed: true

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    override_command: false
    groups:
      - debian

  - name: rocky-instance
    image: "geerlingguy/docker-rockylinux9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /tmp:/tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    override_command: false
    groups:
      - rocky

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "1"
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      host_key_checking: false
      remote_tmp: /tmp/ansible-tmp
      local_tmp: /tmp/ansible-tmp
  playbooks:
    prepare: prepare.yml
  inventory:
    group_vars:
      all:
        ansible_user: ansible
        proxmox_vmid: 9100
        project_root: ${MOLECULE_PROJECT_DIRECTORY}
        report_root: ${MOLECULE_PROJECT_DIRECTORY}/verify_output

        telgraf2influxdb_configs:
          localhost:
            url: "http://127.0.0.1"
            token: ""
            bucket: "telegraf"
            org: "lavnet"
            namedrop: '["influxdb_oss"]'
            bucket_tag: ""
            exclude_bucket_tag: ""
            ping_timeout: "0s"
            read_idle_timeout: "0s"
            insecure_skip_verify: false
        loki_local_storage: true
        influxdb_test: true
        influxdb_configure: true
        alloy_loki_endpoint: "127.0.0.1"

    host_vars:
      debian-instance:
        ansible_connection: docker

      rocky-instance:
        ansible_connection: docker

scenario:
  name: github
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
