---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - gpg
          - ca-certificates
          - lsof
        state: present
        update_cache: yes
      register: apt_result
      retries: 3
      delay: 10
      until: apt_result is success

    # Wait for any automated apt activities to finish
    - name: Wait for dpkg lock
      shell: |
        while lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for apt lock to be released..."
          sleep 5
        done
      changed_when: false
      # Add a reasonable timeout
      async: 300
      poll: 5
