---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check service statuses
      ansible.builtin.service_facts:

    - name: Verify required services are running
      ansible.builtin.assert:
        that:
          - "'influxdb.service' in ansible_facts.services"
          - "ansible_facts.services['influxdb.service'].state == 'running'"
          - "'telegraf.service' in ansible_facts.services"
          - "ansible_facts.services['telegraf.service'].state == 'running'"
          - "'loki.service' in ansible_facts.services"
          - "ansible_facts.services['loki.service'].state == 'running'"
          - "'alloy.service' in ansible_facts.services"
          - "ansible_facts.services['alloy.service'].state == 'running'"

    - name: Check ports
      wait_for:
        port: "{{ item }}"
        timeout: 30
        state: started
      loop:
        - 8086 # InfluxDB
        - 3100 # Loki

    # .....................................................
    - name: Ensure verify_output directory exists
      ansible.builtin.file:
        path: "{{ report_root }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      become: false

    # .................................................................
    - name: Debug directory path
      ansible.builtin.debug:
        msg:
          - "Report root path: {{ report_root }}"
          - "Project root path: {{ project_root }}"
      delegate_to: localhost

    - name: Check directory existence and permissions
      ansible.builtin.stat:
        path: "{{ report_root }}"
      register: dir_check
      delegate_to: localhost

    - name: Debug directory status
      ansible.builtin.debug:
        msg:
          - "Directory exists: {{ dir_check.stat.exists | default(false) }}"
          - "Directory permissions: {{ dir_check.stat.mode | default('N/A') }}"
          - "Directory owner: {{ dir_check.stat.pw_name | default('N/A') }}"
      delegate_to: localhost

    - name: Ensure verify_output directory exists with explicit path
      ansible.builtin.file:
        path: "{{ report_root }}"
        state: directory
        mode: "0755"
        recurse: yes # This will create parent directories if needed
      delegate_to: localhost
      become: false

    # .................................................................
    - name: Save test results
      copy:
        content: |
          === GitHub CI Test Results ===
          Timestamp: {{ ansible_date_time.iso8601 }}

          Service Status:
          - InfluxDB: {{ ansible_facts.services['influxdb.service'].state }}
          - Telegraf: {{ ansible_facts.services['telegraf.service'].state }}
          - Loki: {{ ansible_facts.services['loki.service'].state }}
          - Alloy: {{ ansible_facts.services['alloy.service'].state }}
        dest: "{{ report_root }}/github_ci_results.yml"
        mode: "0644"
