# molecule/verify-clone/prepare.yml
---
- name: Prepare VM
  hosts: localhost
  tasks:
    - name: Start the VM
      community.general.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
        api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
        node: "{{ lookup('env', 'PROXMOX_NODE') }}"
        name: "clone-test"
        state: started
        timeout: 300

    - name: Wait for VM to boot
      pause:
        seconds: 30

    - name: Wait for SSH
      wait_for:
        host: "192.168.101.90"
        port: 22
        timeout: 300

    - name: Display connection status
      debug:
        msg: "VM is ready at 192.168.101.90"

- name: Install prerequisites
  hosts: all
  become: true
  tasks:
    - name: Wait for cloud-init to finish
      shell: cloud-init status
      register: cloud_init_status
      until: "'status: done' in cloud_init_status.stdout"
      retries: 30
      delay: 10

    - name: Install required packages
      apt:
        name:
          - gpg
          - ca-certificates
          - qemu-guest-agent
        update_cache: yes
        state: present

    - name: Ensure qemu-guest-agent is running
      systemd:
        name: qemu-guest-agent
        state: started
        enabled: true
