# .github/workflows/ci.yml
---
name: CI
on:
  push:
    branches: [main, master]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "**.md"

env:
  MOLECULE_NO_LOG: false
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian12
          # - ubuntu2204

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create required directories
        run: |
          mkdir -p log
          mkdir -p verify_output
          chmod 777 log verify_output

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            ansible-core==2.18.1 \
            molecule==24.12.0 \
            molecule-plugins==23.5.3 \
            ansible-lint==24.12.1 \
            yamllint==1.35.1 \
            docker \
            jmespath

      - name: Install galaxy requirements
        run: |
          ansible-galaxy collection install community.general

      - name: Run Molecule tests
        run: molecule test -s github
        env:
          LOG_DURATION: "5m"
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: monitoring-test-results
          path: verify_output
          if-no-files-found: error